version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://15.164.96.99:9092 # Kafka 브로커가 외부 클라이언트에게 광고하는 주소. 클라이언트는 이 주소를 사용하여 Kafka 브로커에 연결
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092 # Kafka 브로커가 수신 대기할 주소. 브로커는 이 주소에서 클라이언트 연결을 수신.
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # Kafka 브로커가 연결할 Zookeeper의 주소. Zookeeper는 Kafka 클러스터의 메타데이터를 관리
    depends_on:
      - zookeeper
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge