spring:
    application: 
        name: kafka-consumer-server

    kafka:
        bootstrap-servers: 15.164.96.99:9092
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            # group-id: kafka-consumer-server
            auto-offset-reset: earliest
server:
    port: 8081